name: build
on: push
jobs:
    job1:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.0'
                architecture: 'x64'
            - name: Install dependencies
              run: python -m ensurepip && python -m pip install --upgrade pip
            - name: PIP Install
              run: pip install minecraft-launcher-lib pyinstaller requests subprocess
            - name: Build
              run: pyinstaller -F -i ico.ico Launcher.py
            - name: Artifact
              uses: actions/upload-artifact@v4
              with:
                name: Launcher
                path: dist/*.exe
